export const SET_AUTHENTICATE = 'SET_AUTHENTICATE';
export const SET_DATA_TRACKING = 'SET_DATA_TRACKING';
export const SET_WAYBILLNUMBER = 'SET_WAYBILLNUMBER';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_SEARCHPARAM = 'SET_SEARCHPARAM';
export const SET_READYSEARCHPARAM = 'SET_READYSEARCHPARAM';



